[package]
name = "rs_zero2prod"
version = "0.1.0"
authors = ["dxps <marius.ileana@gmail.com>"]
edition = "2018"


[lib]
path = "src/lib.rs"


[[bin]]
path = "src/main.rs"
name = "rs_zero2prod"


[dependencies]
actix-web = "4.0.0-beta.4"

[dev-dependencies]
actix-rt = "2"
reqwest = "0.11"
tokio = "1"

