[package]
authors = ["dxps <marius.ileana@gmail.com>"]
edition = "2018"
name = "rs_zero2prod"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ztp-rs"
path = "src/main.rs"

[dependencies]
actix-http = "3.0.0-beta.11"
actix-web = "4.0.0-beta.10"
serde = {version = "1", features = ["derive"]}

[dev-dependencies]
actix-rt = "2"
reqwest = "0.11"
tokio = "1"
