database:
    host: "localhost"
    port: 5440
    username: "postgres"
    password: "postgres"
    name: "ztp_newsletter"

email_client:
    api_base_url: "localhost"
    sender_email: "local@gmail.com"

http:
    port: 8000
